# Generated by Django 4.0.4 on 2023-01-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_msg_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
