# Generated by Django 4.0.4 on 2023-01-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': '-created_at'},
        ),
    ]
