# Generated by Django 4.0.4 on 2023-01-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'created_at'},
        ),
    ]
