# Generated by Django 4.0.4 on 2023-01-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_message_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='message',
            name='is_sended',
            field=models.BooleanField(default=True),
        ),
    ]
