# Generated by Django 4.0.4 on 2022-12-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='indentity_number',
        ),
    ]
