# Generated by Django 4.0.4 on 2022-12-17 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('user', '0003_remove_customuser_indentity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='indentity_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.identitynumber'),
            preserve_default=False,
        ),
    ]
