# Generated by Django 4.0.4 on 2022-12-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_indentity_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='indentity_number',
        ),
    ]
