# Generated by Django 4.0.4 on 2022-12-19 12:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('RENTER', 'Renter'), ('RENT_RECEIVER', 'Rent Receiver')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
