# Generated by Django 4.0.4 on 2022-12-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=None, max_length=50, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('RENTER', 'Renter'), ('RENT_RECEIVER', 'Rent Receiver')], max_length=30, null=True),
        ),
    ]
