# Generated by Django 4.0.4 on 2022-12-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customuser_is_active_customuser_is_secure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
    ]
