# Generated by Django 4.0.4 on 2022-12-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_identitynumber_birth_date_and_more'),
        ('user', '0012_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='indentity_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='document.identitynumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('RENTER', 'Renter'), ('RENT_RECEIVER', 'Rent Receiver')], max_length=30, null=True),
        ),
    ]
