# Generated by Django 4.0.4 on 2023-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('RENTER', 'Renter'), ('RECEIVER', 'Receiver')], max_length=30, null=True),
        ),
    ]
