# Generated by Django 4.0.4 on 2022-12-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indentity_number', models.CharField(max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_place', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Esp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp', models.FileField(unique=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField()),
                ('indentity_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.identitynumber')),
            ],
        ),
    ]
