# Generated by Django 4.0.4 on 2022-12-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitynumber',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='identitynumber',
            name='birth_place',
        ),
        migrations.AddField(
            model_name='identitynumber',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='identitynumber',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='identitynumber',
            name='patronymic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='identitynumber',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
