# Generated by Django 4.0.4 on 2023-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_esp_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp',
            name='hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
