# Generated by Django 4.0.4 on 2023-01-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_esp_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp',
            name='hash',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
