# Generated by Django 4.0.4 on 2023-01-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_receiver_alter_contract_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_signed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('SENDED', 'Sended'), ('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CREATED', 'Created')], default='CREATED', max_length=10, null=True),
        ),
    ]
