# Generated by Django 4.0.4 on 2023-01-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contracttemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='is_signed',
            new_name='is_signed_by_receiver',
        ),
        migrations.AddField(
            model_name='contract',
            name='is_signed_by_renter',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
