# Generated by Django 4.0.4 on 2023-01-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_rename_is_signed_contract_is_signed_by_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('SENDED', 'Sended'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='CREATED', max_length=10, null=True),
        ),
    ]
